version: '3'
services:
  easy-continuity-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19002:19002"
    environment:
      - NODE_ENV=development