version: '3.9'
services:
  easy-continuity-staging:
    build: 
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19002:19002"
    environment: 
      - NODE_ENV=staging
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LINODE_IP}
      - ENDPOINT_URL=http://${LINODE_IP}:5003
    command: npx expo start --web --lan --port 19000
    network_mode: "host"