version: '3'
services:
  easy-continuity-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19002:19002"
    environment:
      - NODE_ENV=development
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LINODE_IP}
    command: npx expo start --web --lan --port 19000
    network_mode: "host"