name: Manual Merge to Staging

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm merge to staging'
        required: true

jobs:
  merge_to_preprod:
    if: github.event.inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetches the entire history of the repository. Without it only fetch-depth:1 happens

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.15.0'

    - name: Merge preprod to main
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout preprod
        git pull origin preprod
        git checkout main
        git merge --no-ff preprod
        git push origin main

    - name: Deploy to Linode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USER }}
        key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd EasyContinuity-Mobile
          git checkout preprod
          git pull origin preprod
          git checkout main
          git merge preprod
          docker compose -f docker-compose.uat.yml down
          docker compose -f docker-compose.staging.yml up -d --build