name: Merge PR to Dev and Deploy to UAT

on:
  push:
    branches: [ dev ]

jobs:
  deploy_to_uat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetches the entire history of the repository

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.15.0'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      continue-on-error: false
      
    - name: Merge dev to uat
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout dev
        git pull origin dev
        git checkout uat
        git pull origin uat
        git merge --no-ff dev -m "Merge dev into uat [skip ci]"
        git push origin uat

    - name: Deploy to UAT Environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USER }}
        key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Stop all related containers
          docker ps | grep "easycontinuity" | awk '{print $1}' | xargs docker stop || true
          
          # Start API containers
          cd EasyContinuity-API_UAT
          docker compose -f docker-compose.uat.yml up -d --build
          
          # Update and deploy Mobile for UAT
          cd ../EasyContinuity-Mobile
          git fetch --all
          git checkout uat
          git pull origin uat
          docker compose -f docker-compose.uat.yml up -d --build