name: Deploy to UAT

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm deployment to UAT'
        required: true

jobs:
  deploy_to_uat:
    if: github.event.inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetches the entire history of the repository

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.15.0'

    - name: Merge test to uat
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout test
        git pull origin test
        git checkout uat
        git pull origin uat
        git merge --no-ff test -m "Merge test into uat [skip ci]"
        git push origin uat

    - name: Deploy to UAT Environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USER }}
        key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Stop all related containers
          docker ps | grep "easycontinuity" | awk '{print $1}' | xargs docker stop || true
          
          # Start API containers
          cd EasyContinuity-API_UAT
          docker compose -f docker-compose.uat.yml up -d --build
          
          # Update and deploy Mobile for UAT
          cd ../EasyContinuity-Mobile
          git fetch --all
          git checkout uat
          git pull origin uat
          docker compose -f docker-compose.uat.yml up -d --build